name: PHP Tests

on:
    push:
    schedule:
        - cron: '0 0 * * *'

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            # if one job fails, abort the next ones too, because they'll probably fail - best to save the minutes
            fail-fast: false  # to change to: true

            # run all combinations of the following, to make sure they're working together
            matrix:
                # os: [ubuntu-latest, macos-latest, windows-latest]
                php: [7.2, 7.3, 7.4, 8.0]
                dbal: [^2.5, ^3.0]
                laravel: [6.*, 7.*, 8.*]
                phpunit: [8.*, 9.*]
                dependency-version: [stable] # to add: lowest
                exclude:
                    -   php: 7.2
                        phpunit: 9.*
                    -   laravel: 8.*
                        php: 7.2
                    -   laravel: 8.*
                        phpunit: 8.*
                    -   php: 7.2
                        dbal: ^3.0
                    -   dbal: ^3.0
                        laravel: 6.*
                    -   dbal: ^3.0
                        laravel: 7.*

        name: PHP ${{ matrix.php }}, Laravel ${{ matrix.laravel }}, PHPUnit ${{ matrix.phpunit }}, DBAL ${{ matrix.dbal }} --prefer-${{ matrix.dependency-version }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Install SQLite 3
                run: |
                    sudo apt-get update
                    sudo apt-get install sqlite3
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
                    coverage: xdebug
            -   name: Cache dependencies
                uses: actions/cache@v1
                with:
                    path: ~/.composer/cache/files
                    key: dependencies-${{ matrix.dependency-version }}-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-phpunit-${{ matrix.phpunit }}-composer-${{ hashFiles('composer.json') }}
            -   name: Install dependencies
                run: |
                    composer require "laravel/framework:${{ matrix.laravel }}" "phpunit/phpunit:${{ matrix.phpunit }}" "doctrine/dbal:${{ matrix.dbal }}" --no-interaction --no-update
                    composer update --prefer-${{ matrix.dependency-version }} --prefer-dist --no-interaction
            -   name: Execute tests
                run: composer test
    coverage:
        needs: [ test ]
        name: coverage
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - uses: actions/setup-node@master
            with:
              node-version: '12'
          - run: npm install -g yarn
          - run: yarn install
          - run: yarn build
          - uses: paambaati/codeclimate-action@v2.2.4
          env:
            CC_TEST_REPORTER_ID: 945dfb58a832d233a3caeb84e3e6d3be212e8c7abcb48117fce63b9adcb43647
          with:
            coverageCommand: yarn coverage
