name: PHP Tests

on:
    push:
    schedule:
        - cron: '0 0 * * *'

jobs:
    coverage:
        name: Coverage
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Install SQLite 3
                run: |
                  sudo apt-get update
                  sudo apt-get install sqlite3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                  php-version: 8.0
                  extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
                  coverage: none

            -   name: Cache dependencies
                uses: actions/cache@v1
                with:
                  path: ~/.composer/cache/files
                  key: dependencies-${{ matrix.dependency-version }}-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-phpunit-${{ matrix.phpunit }}-composer-${{ hashFiles('composer.json') }}

            -   name: Install dependencies
                run: |
                  composer update --prefer-dist --no-interaction

            -   name: Install Node
                uses: actions/setup-node@master
                with:
                  node-version: '12'

            -   name: Coverage
                uses: paambaati/codeclimate-action@v2.7.5
                env:
                    CC_TEST_REPORTER_ID: 7b4c081a17ad129d9a8e65c31623b640c7975c461ec307b0082cacaccf2e450a
                with:
                    coverageCommand: phpunit --coverage-clover coverage.xml
